import { z } from "zod";
import type { Product } from "@/types/product";
const productSchema = z.object({ id:z.number(),sku:z.string(),name:z.string(),brand:z.string(),category:z.string(),description:z.string().nullable(),price:z.coerce.number(),stock_quantity:z.number(),is_active:z.boolean() });
const userSchema = z.object({ id:z.number(),name:z.string(),email:z.string().email(),role:z.string() });
const customerSchema = userSchema.extend({ phone:z.string().nullable(),is_active:z.boolean(),created_at:z.string(),updated_at:z.string() });
const ticketPreviewSchema = z.object({ id:z.number(),ticket_number:z.string(),subject:z.string(),description:z.string(),status:z.string(),priority:z.string(),assigned_to:z.string().nullable(),created_at:z.string(),updated_at:z.string(),order:z.object({order_number:z.string(),status:z.string()}).nullable() });
const ticketSchema = ticketPreviewSchema.extend({ customer:z.object({id:z.number(),name:z.string(),email:z.string(),phone:z.string().nullable()}),order:z.object({order_number:z.string()}).nullable() });
const orderSchema = z.object({ id:z.number(),order_number:z.string(),status:z.string(),subtotal:z.coerce.number(),shipping_fee:z.coerce.number(),discount:z.coerce.number(),total_amount:z.coerce.number(),shipping_address:z.string(),tracking_number:z.string().nullable(),created_at:z.string(),updated_at:z.string(),customer:z.object({id:z.number(),name:z.string(),email:z.string(),phone:z.string().nullable()}),items:z.array(z.object({id:z.number(),quantity:z.number(),unit_price:z.coerce.number(),total_price:z.coerce.number(),product:z.object({id:z.number(),sku:z.string(),name:z.string(),brand:z.string(),category:z.string(),price:z.coerce.number()})})),payment:z.object({id:z.number(),payment_method:z.string(),payment_status:z.string(),transaction_id:z.string().nullable(),amount:z.coerce.number(),paid_at:z.string().nullable(),refunds:z.array(z.object({id:z.number(),refund_status:z.string(),amount:z.coerce.number(),refund_transaction_id:z.string().nullable(),reason:z.string().nullable(),processed_at:z.string().nullable()}))}).nullable() });
const ragSchema = z.object({ answer:z.string(),sources:z.array(z.object({source:z.string(),score:z.number()})),status:z.string() });
const cancellationSchema=z.object({order_number:z.string(),previous_status:z.string(),new_status:z.string(),message:z.string()}); const refundSchema=z.object({order_number:z.string(),refund_status:z.string().nullable(),refund_amount:z.coerce.number().nullable(),refund_transaction_id:z.string().nullable(),reason:z.string().nullable(),processed_at:z.string().nullable(),created_at:z.string().nullable(),updated_at:z.string().nullable(),payment_status:z.string().nullable(),payment_method:z.string().nullable(),message:z.string()});
export type User=z.infer<typeof userSchema>; export type Customer=z.infer<typeof customerSchema>; export type Order=z.infer<typeof orderSchema>; export type Ticket=z.infer<typeof ticketSchema>; export type TicketPreview=z.infer<typeof ticketPreviewSchema>; export type RagResponse=z.infer<typeof ragSchema>;
export class ApiError extends Error { constructor(public status:number,message:string){super(message)} }
function token(){return typeof window === "undefined" ? null : localStorage.getItem("electromart_token")}
async function request<T>(path:string,schema:z.ZodType<T>,options:RequestInit={},authenticated=false):Promise<T>{const accessToken=authenticated?token():null;const response=await fetch(path,{...options,headers:{"Content-Type":"application/json",...(accessToken?{Authorization:`Bearer ${accessToken}`}:{ }),...options.headers}});if(!response.ok){const payload=await response.json().catch(()=>null);const message=typeof payload?.detail==="string"?payload.detail:response.status===401?"Your session has expired. Please sign in again.":"Something went wrong. Please try again.";if(response.status===401&&typeof window!=="undefined")window.dispatchEvent(new Event("electromart:unauthorized"));throw new ApiError(response.status,message)}return schema.parse(await response.json())}
export const productsApi={list:()=>request("/api/products",z.array(productSchema)),detail:(id:string)=>request(`/api/products/${id}`,productSchema),search:(query:string)=>request(`/api/products/search?name=${encodeURIComponent(query)}`,z.array(productSchema))};
export const authApi={login:(email:string,password:string)=>request("/api/auth/login",z.object({access_token:z.string(),token_type:z.string()}),{method:"POST",body:JSON.stringify({email,password})}),register:(data:{name:string;email:string;password:string;phone?:string})=>request("/api/auth/register",userSchema,{method:"POST",body:JSON.stringify(data)}),me:()=>request("/api/auth/me",userSchema,{},true)};
export const customerApi={profile:(id:number)=>request(`/api/customers/${id}`,customerSchema,{},true),orders:(id:number)=>request(`/api/customers/${id}/orders`,z.array(orderSchema),{},true),tickets:(id:number)=>request(`/api/customers/${id}/tickets`,z.array(ticketPreviewSchema),{},true)};
export const ordersApi={detail:(number:string)=>request(`/api/orders/${number}`,orderSchema,{},true),cancel:(number:string)=>request(`/api/orders/${number}/cancel`,cancellationSchema,{method:"POST"},true),refund:(number:string)=>request(`/api/orders/${number}/refund`,refundSchema,{},true)};
export const ticketsApi={detail:(number:string)=>request(`/api/tickets/${number}`,ticketSchema,{},true),create:(data:{customer_id:number;order_number?:string;subject:string;description:string;priority:string})=>request("/api/tickets",ticketSchema,{method:"POST",body:JSON.stringify(data)},true),update:(number:string,data:{subject?:string;description?:string;status?:string;priority?:string})=>request(`/api/tickets/${number}`,ticketSchema,{method:"PATCH",body:JSON.stringify(data)},true)};
export const ragApi={query:(query:string)=>request("/api/rag/query",ragSchema,{method:"POST",body:JSON.stringify({query})})};
export type { Product };
